### ISSUE TITLE
ERROR IN KEYLOGGER FUNCTION

### ISSUE THREAD

**Issue by VaradScript** [haydenbanz/DiscordGloom#15]
# Bug Report

**Project:** [HadesConnect](https://github.com/haydenbanz/HadesConnect)  
**Repository URL:** https://github.com/haydenbanz/HadesConnect

## Description

*A clear and concise description of what the bug is.*
`s never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019CAEFFF670>
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed`

## Additional Context

*Add any other context about the problem here.*

---

**Note:** Please check the existing issues before reporting a new one to avoid duplicates.

**Comment by Glitchesminds** [comment]
That function is removed as if now

**Comment by h9zdev** [comment]
> That function is removed as if now

This function is removed as if now further it will be updated
